[compiler.solc]
ignore_paths = ["source/node_modules", "source/lib", "source/test", "source/script"]
include_paths = ["source/node_modules"]
remappings = [
    "src/=source/src/",
    "@openzeppelin/=source/lib/@openzeppelin/contracts/",
    "@openzeppelin/contracts/=source/lib/@openzeppelin/contracts/",
    "balancer/=source/lib/balancer/src/",
    "canonical-weth/=source/lib/canonical-weth/src/",
    "cowprotocol/=source/lib/cowprotocol/src/contracts/",
    "ds-test/=source/lib/forge-std/lib/ds-test/src/",
    "erc4626-tests/=source/lib/@openzeppelin/lib/erc4626-tests/",
    "forge-std/=source/lib/forge-std/src/",
    "helpers/=source/lib/balancer/src/lib/helpers/",
    "math/=source/lib/balancer/src/lib/math/",
    "murky/=source/lib/murky/src/",
    "openzeppelin-contracts/=source/lib/murky/lib/openzeppelin-contracts/",
    "openzeppelin/=source/lib/@openzeppelin/contracts/",
    "safe/=source/lib/safe/contracts/",
]
evm_version = "paris"

[compiler.solc.optimizer]
enabled = true
runs = 20000
